### PR TITLE
Now script takes leap-years into account

### LINKED ISSUE #1: Allow this script to take leap-years into account.
Currently, this script doesn't take leap-years into account for the day calculation. This should be able to easily be fixed with a single function. Leaving this open for new users or if you want to contribute for Hacktoberfest.

### PR DESCRIPTION
**Pull request by angelbarrera92**
Fix #1

### CODE REVIEW

**Comment by sklusz** [comment]
I should have @ you when I posted this in the issue, but this doesn't exactly fix the problem.

Copying this from another comment:

When there's a leap year, there is a 29th day of February. Normally March 1st is the 60th day of the year, but on leap years March 1st is the 61st day of the year.

There should be some way to have March 1st still be Wallpaper number 60, instead of Wallpaper number 61 on a leap year. It's not necessary to allow a user to set a unique wallpaper for February 29th (so it's only shown on leap years) but if you would like to do that somehow, go ahead.

**Comment by angelbarrera92** [comment]
I will take a look!

**Comment by angelbarrera92** [comment]
I have pushed a new commit. Take a look please! @tklusz

**Comment by sklusz** [comment]
Going to merge this then change a couple lines. Thanks.

**Pull request merged**
